// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeInfo struct {
	ProtocolVersion      *NodeInfo_ProtocolVersion `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListenAddr           string                    `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Network              string                    `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Version              string                    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Channels             string                    `protobuf:"bytes,5,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker              string                    `protobuf:"bytes,6,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other                *NodeInfo_Other           `protobuf:"bytes,7,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetProtocolVersion() *NodeInfo_ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

func (m *NodeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *NodeInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeInfo) GetChannels() string {
	if m != nil {
		return m.Channels
	}
	return ""
}

func (m *NodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *NodeInfo) GetOther() *NodeInfo_Other {
	if m != nil {
		return m.Other
	}
	return nil
}

type NodeInfo_ProtocolVersion struct {
	P2P                  uint64   `protobuf:"varint,3,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Block                uint64   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	App                  uint64   `protobuf:"varint,2,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo_ProtocolVersion) Reset()         { *m = NodeInfo_ProtocolVersion{} }
func (m *NodeInfo_ProtocolVersion) String() string { return proto.CompactTextString(m) }
func (*NodeInfo_ProtocolVersion) ProtoMessage()    {}
func (*NodeInfo_ProtocolVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0, 0}
}

func (m *NodeInfo_ProtocolVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Unmarshal(m, b)
}
func (m *NodeInfo_ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Marshal(b, m, deterministic)
}
func (m *NodeInfo_ProtocolVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo_ProtocolVersion.Merge(m, src)
}
func (m *NodeInfo_ProtocolVersion) XXX_Size() int {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Size(m)
}
func (m *NodeInfo_ProtocolVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo_ProtocolVersion.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo_ProtocolVersion proto.InternalMessageInfo

func (m *NodeInfo_ProtocolVersion) GetP2P() uint64 {
	if m != nil {
		return m.P2P
	}
	return 0
}

func (m *NodeInfo_ProtocolVersion) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *NodeInfo_ProtocolVersion) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type NodeInfo_Other struct {
	TxIndex              string   `protobuf:"bytes,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	RpcAddress           string   `protobuf:"bytes,1,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo_Other) Reset()         { *m = NodeInfo_Other{} }
func (m *NodeInfo_Other) String() string { return proto.CompactTextString(m) }
func (*NodeInfo_Other) ProtoMessage()    {}
func (*NodeInfo_Other) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0, 1}
}

func (m *NodeInfo_Other) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo_Other.Unmarshal(m, b)
}
func (m *NodeInfo_Other) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo_Other.Marshal(b, m, deterministic)
}
func (m *NodeInfo_Other) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo_Other.Merge(m, src)
}
func (m *NodeInfo_Other) XXX_Size() int {
	return xxx_messageInfo_NodeInfo_Other.Size(m)
}
func (m *NodeInfo_Other) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo_Other.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo_Other proto.InternalMessageInfo

func (m *NodeInfo_Other) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (m *NodeInfo_Other) GetRpcAddress() string {
	if m != nil {
		return m.RpcAddress
	}
	return ""
}

type NetInfoResponse struct {
	Jsonrpc              string                  `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id                   string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result               *NetInfoResponse_Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetInfoResponse) Reset()         { *m = NetInfoResponse{} }
func (m *NetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse) ProtoMessage()    {}
func (*NetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1}
}

func (m *NetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse.Unmarshal(m, b)
}
func (m *NetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse.Merge(m, src)
}
func (m *NetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse.Size(m)
}
func (m *NetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse proto.InternalMessageInfo

func (m *NetInfoResponse) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *NetInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetInfoResponse) GetResult() *NetInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type NetInfoResponse_Result struct {
	Listening            bool                           `protobuf:"varint,4,opt,name=listening,proto3" json:"listening,omitempty"`
	Listeners            []string                       `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	NPeers               int64                          `protobuf:"varint,2,opt,name=n_peers,json=nPeers,proto3" json:"n_peers,omitempty"`
	Peers                []*NetInfoResponse_Result_Peer `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *NetInfoResponse_Result) Reset()         { *m = NetInfoResponse_Result{} }
func (m *NetInfoResponse_Result) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse_Result) ProtoMessage()    {}
func (*NetInfoResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1, 0}
}

func (m *NetInfoResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Result.Unmarshal(m, b)
}
func (m *NetInfoResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Result.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Result.Merge(m, src)
}
func (m *NetInfoResponse_Result) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Result.Size(m)
}
func (m *NetInfoResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Result proto.InternalMessageInfo

func (m *NetInfoResponse_Result) GetListening() bool {
	if m != nil {
		return m.Listening
	}
	return false
}

func (m *NetInfoResponse_Result) GetListeners() []string {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (m *NetInfoResponse_Result) GetNPeers() int64 {
	if m != nil {
		return m.NPeers
	}
	return 0
}

func (m *NetInfoResponse_Result) GetPeers() []*NetInfoResponse_Result_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type NetInfoResponse_Result_Peer struct {
	NodeInfo             *NodeInfo                                     `protobuf:"bytes,4,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	IsOutbound           bool                                          `protobuf:"varint,1,opt,name=is_outbound,json=isOutbound,proto3" json:"is_outbound,omitempty"`
	ConnectionStatus     *NetInfoResponse_Result_Peer_ConnectionStatus `protobuf:"bytes,2,opt,name=connection_status,json=connectionStatus,proto3" json:"connection_status,omitempty"`
	RemoteIp             string                                        `protobuf:"bytes,3,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *NetInfoResponse_Result_Peer) Reset()         { *m = NetInfoResponse_Result_Peer{} }
func (m *NetInfoResponse_Result_Peer) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse_Result_Peer) ProtoMessage()    {}
func (*NetInfoResponse_Result_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1, 0, 0}
}

func (m *NetInfoResponse_Result_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Result_Peer.Unmarshal(m, b)
}
func (m *NetInfoResponse_Result_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Result_Peer.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Result_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Result_Peer.Merge(m, src)
}
func (m *NetInfoResponse_Result_Peer) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Result_Peer.Size(m)
}
func (m *NetInfoResponse_Result_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Result_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Result_Peer proto.InternalMessageInfo

func (m *NetInfoResponse_Result_Peer) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *NetInfoResponse_Result_Peer) GetIsOutbound() bool {
	if m != nil {
		return m.IsOutbound
	}
	return false
}

func (m *NetInfoResponse_Result_Peer) GetConnectionStatus() *NetInfoResponse_Result_Peer_ConnectionStatus {
	if m != nil {
		return m.ConnectionStatus
	}
	return nil
}

func (m *NetInfoResponse_Result_Peer) GetRemoteIp() string {
	if m != nil {
		return m.RemoteIp
	}
	return ""
}

type NetInfoResponse_Result_Peer_ConnectionStatus struct {
	Duration             int64                                                   `protobuf:"varint,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	SendMonitor          *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor   `protobuf:"bytes,1,opt,name=SendMonitor,proto3" json:"SendMonitor,omitempty"`
	RecvMonitor          *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor   `protobuf:"bytes,2,opt,name=RecvMonitor,proto3" json:"RecvMonitor,omitempty"`
	Channels             []*NetInfoResponse_Result_Peer_ConnectionStatus_Channel `protobuf:"bytes,3,rep,name=Channels,proto3" json:"Channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                `json:"-"`
	XXX_unrecognized     []byte                                                  `json:"-"`
	XXX_sizecache        int32                                                   `json:"-"`
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus) Reset() {
	*m = NetInfoResponse_Result_Peer_ConnectionStatus{}
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Result_Peer_ConnectionStatus) ProtoMessage() {}
func (*NetInfoResponse_Result_Peer_ConnectionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1, 0, 0, 0}
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus.Unmarshal(m, b)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus.Merge(m, src)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus.Size(m)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus proto.InternalMessageInfo

func (m *NetInfoResponse_Result_Peer_ConnectionStatus) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus) GetSendMonitor() *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor {
	if m != nil {
		return m.SendMonitor
	}
	return nil
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus) GetRecvMonitor() *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor {
	if m != nil {
		return m.RecvMonitor
	}
	return nil
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus) GetChannels() []*NetInfoResponse_Result_Peer_ConnectionStatus_Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type NetInfoResponse_Result_Peer_ConnectionStatus_Monitor struct {
	Active               bool     `protobuf:"varint,13,opt,name=Active,proto3" json:"Active,omitempty"`
	Start                string   `protobuf:"bytes,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Idle                 int64    `protobuf:"varint,3,opt,name=Idle,proto3" json:"Idle,omitempty"`
	Bytes                int64    `protobuf:"varint,4,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Samples              int64    `protobuf:"varint,5,opt,name=Samples,proto3" json:"Samples,omitempty"`
	InstRate             int64    `protobuf:"varint,6,opt,name=InstRate,proto3" json:"InstRate,omitempty"`
	CurRate              int64    `protobuf:"varint,7,opt,name=CurRate,proto3" json:"CurRate,omitempty"`
	AvgRate              int64    `protobuf:"varint,8,opt,name=AvgRate,proto3" json:"AvgRate,omitempty"`
	PeakRate             int64    `protobuf:"varint,9,opt,name=PeakRate,proto3" json:"PeakRate,omitempty"`
	BytesRem             int64    `protobuf:"varint,10,opt,name=BytesRem,proto3" json:"BytesRem,omitempty"`
	TimeRem              int64    `protobuf:"varint,11,opt,name=TimeRem,proto3" json:"TimeRem,omitempty"`
	Progress             uint32   `protobuf:"varint,12,opt,name=Progress,proto3" json:"Progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) Reset() {
	*m = NetInfoResponse_Result_Peer_ConnectionStatus_Monitor{}
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) ProtoMessage() {}
func (*NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1, 0, 0, 0, 0}
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Monitor.Unmarshal(m, b)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Monitor.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Monitor.Merge(m, src)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Monitor.Size(m)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Monitor proto.InternalMessageInfo

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetIdle() int64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetSamples() int64 {
	if m != nil {
		return m.Samples
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetInstRate() int64 {
	if m != nil {
		return m.InstRate
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetCurRate() int64 {
	if m != nil {
		return m.CurRate
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetAvgRate() int64 {
	if m != nil {
		return m.AvgRate
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetPeakRate() int64 {
	if m != nil {
		return m.PeakRate
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetBytesRem() int64 {
	if m != nil {
		return m.BytesRem
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetTimeRem() int64 {
	if m != nil {
		return m.TimeRem
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Monitor) GetProgress() uint32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type NetInfoResponse_Result_Peer_ConnectionStatus_Channel struct {
	ID                   int32    `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	SendQueueCapacity    int64    `protobuf:"varint,1,opt,name=SendQueueCapacity,proto3" json:"SendQueueCapacity,omitempty"`
	SendQueueSize        int64    `protobuf:"varint,2,opt,name=SendQueueSize,proto3" json:"SendQueueSize,omitempty"`
	Priority             int64    `protobuf:"varint,3,opt,name=Priority,proto3" json:"Priority,omitempty"`
	RecentlySent         int64    `protobuf:"varint,4,opt,name=RecentlySent,proto3" json:"RecentlySent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) Reset() {
	*m = NetInfoResponse_Result_Peer_ConnectionStatus_Channel{}
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Result_Peer_ConnectionStatus_Channel) ProtoMessage() {}
func (*NetInfoResponse_Result_Peer_ConnectionStatus_Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1, 0, 0, 0, 1}
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Channel.Unmarshal(m, b)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Channel.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Channel.Merge(m, src)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Channel.Size(m)
}
func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Result_Peer_ConnectionStatus_Channel proto.InternalMessageInfo

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) GetSendQueueCapacity() int64 {
	if m != nil {
		return m.SendQueueCapacity
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) GetSendQueueSize() int64 {
	if m != nil {
		return m.SendQueueSize
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *NetInfoResponse_Result_Peer_ConnectionStatus_Channel) GetRecentlySent() int64 {
	if m != nil {
		return m.RecentlySent
	}
	return 0
}

type StatusResponse struct {
	Jsonrpc              string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id                   string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result               *StatusResponse_Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *StatusResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StatusResponse) GetResult() *StatusResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type StatusResponse_Result struct {
	Version              string                          `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	LatestBlockHash      string                          `protobuf:"bytes,1,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	LatestAppHash        string                          `protobuf:"bytes,2,opt,name=latest_app_hash,json=latestAppHash,proto3" json:"latest_app_hash,omitempty"`
	LatestBlockHeight    int64                           `protobuf:"varint,3,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height,omitempty"`
	LatestBlockTime      string                          `protobuf:"bytes,4,opt,name=latest_block_time,json=latestBlockTime,proto3" json:"latest_block_time,omitempty"`
	KeepLastStates       int64                           `protobuf:"varint,5,opt,name=keep_last_states,json=keepLastStates,proto3" json:"keep_last_states,omitempty"`
	TmStatus             *StatusResponse_Result_TmStatus `protobuf:"bytes,6,opt,name=tm_status,json=tmStatus,proto3" json:"tm_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *StatusResponse_Result) Reset()         { *m = StatusResponse_Result{} }
func (m *StatusResponse_Result) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_Result) ProtoMessage()    {}
func (*StatusResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2, 0}
}

func (m *StatusResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Result.Unmarshal(m, b)
}
func (m *StatusResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Result.Marshal(b, m, deterministic)
}
func (m *StatusResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Result.Merge(m, src)
}
func (m *StatusResponse_Result) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Result.Size(m)
}
func (m *StatusResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Result proto.InternalMessageInfo

func (m *StatusResponse_Result) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatusResponse_Result) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *StatusResponse_Result) GetLatestAppHash() string {
	if m != nil {
		return m.LatestAppHash
	}
	return ""
}

func (m *StatusResponse_Result) GetLatestBlockHeight() int64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusResponse_Result) GetLatestBlockTime() string {
	if m != nil {
		return m.LatestBlockTime
	}
	return ""
}

func (m *StatusResponse_Result) GetKeepLastStates() int64 {
	if m != nil {
		return m.KeepLastStates
	}
	return 0
}

func (m *StatusResponse_Result) GetTmStatus() *StatusResponse_Result_TmStatus {
	if m != nil {
		return m.TmStatus
	}
	return nil
}

type StatusResponse_Result_TmStatus struct {
	NodeInfo             *NodeInfo                                     `protobuf:"bytes,3,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	SyncInfo             *StatusResponse_Result_TmStatus_SyncInfo      `protobuf:"bytes,1,opt,name=sync_info,json=syncInfo,proto3" json:"sync_info,omitempty"`
	ValidatorInfo        *StatusResponse_Result_TmStatus_ValidatorInfo `protobuf:"bytes,2,opt,name=validator_info,json=validatorInfo,proto3" json:"validator_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *StatusResponse_Result_TmStatus) Reset()         { *m = StatusResponse_Result_TmStatus{} }
func (m *StatusResponse_Result_TmStatus) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_Result_TmStatus) ProtoMessage()    {}
func (*StatusResponse_Result_TmStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2, 0, 0}
}

func (m *StatusResponse_Result_TmStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Result_TmStatus.Unmarshal(m, b)
}
func (m *StatusResponse_Result_TmStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Result_TmStatus.Marshal(b, m, deterministic)
}
func (m *StatusResponse_Result_TmStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Result_TmStatus.Merge(m, src)
}
func (m *StatusResponse_Result_TmStatus) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Result_TmStatus.Size(m)
}
func (m *StatusResponse_Result_TmStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Result_TmStatus.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Result_TmStatus proto.InternalMessageInfo

func (m *StatusResponse_Result_TmStatus) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *StatusResponse_Result_TmStatus) GetSyncInfo() *StatusResponse_Result_TmStatus_SyncInfo {
	if m != nil {
		return m.SyncInfo
	}
	return nil
}

func (m *StatusResponse_Result_TmStatus) GetValidatorInfo() *StatusResponse_Result_TmStatus_ValidatorInfo {
	if m != nil {
		return m.ValidatorInfo
	}
	return nil
}

type StatusResponse_Result_TmStatus_SyncInfo struct {
	LatestBlockHash      string   `protobuf:"bytes,5,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	LatestAppHash        string   `protobuf:"bytes,1,opt,name=latest_app_hash,json=latestAppHash,proto3" json:"latest_app_hash,omitempty"`
	LatestBlockHeight    int64    `protobuf:"varint,2,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height,omitempty"`
	LatestBlockTime      string   `protobuf:"bytes,3,opt,name=latest_block_time,json=latestBlockTime,proto3" json:"latest_block_time,omitempty"`
	CatchingUp           bool     `protobuf:"varint,4,opt,name=catching_up,json=catchingUp,proto3" json:"catching_up,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_Result_TmStatus_SyncInfo) Reset() {
	*m = StatusResponse_Result_TmStatus_SyncInfo{}
}
func (m *StatusResponse_Result_TmStatus_SyncInfo) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_Result_TmStatus_SyncInfo) ProtoMessage()    {}
func (*StatusResponse_Result_TmStatus_SyncInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2, 0, 0, 0}
}

func (m *StatusResponse_Result_TmStatus_SyncInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_SyncInfo.Unmarshal(m, b)
}
func (m *StatusResponse_Result_TmStatus_SyncInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_SyncInfo.Marshal(b, m, deterministic)
}
func (m *StatusResponse_Result_TmStatus_SyncInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Result_TmStatus_SyncInfo.Merge(m, src)
}
func (m *StatusResponse_Result_TmStatus_SyncInfo) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_SyncInfo.Size(m)
}
func (m *StatusResponse_Result_TmStatus_SyncInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Result_TmStatus_SyncInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Result_TmStatus_SyncInfo proto.InternalMessageInfo

func (m *StatusResponse_Result_TmStatus_SyncInfo) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *StatusResponse_Result_TmStatus_SyncInfo) GetLatestAppHash() string {
	if m != nil {
		return m.LatestAppHash
	}
	return ""
}

func (m *StatusResponse_Result_TmStatus_SyncInfo) GetLatestBlockHeight() int64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusResponse_Result_TmStatus_SyncInfo) GetLatestBlockTime() string {
	if m != nil {
		return m.LatestBlockTime
	}
	return ""
}

func (m *StatusResponse_Result_TmStatus_SyncInfo) GetCatchingUp() bool {
	if m != nil {
		return m.CatchingUp
	}
	return false
}

type StatusResponse_Result_TmStatus_ValidatorInfo struct {
	Address              string                                               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	VotingPower          int64                                                `protobuf:"varint,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo) Reset() {
	*m = StatusResponse_Result_TmStatus_ValidatorInfo{}
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo) String() string {
	return proto.CompactTextString(m)
}
func (*StatusResponse_Result_TmStatus_ValidatorInfo) ProtoMessage() {}
func (*StatusResponse_Result_TmStatus_ValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2, 0, 0, 1}
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo.Unmarshal(m, b)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo.Marshal(b, m, deterministic)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo.Merge(m, src)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo.Size(m)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo proto.InternalMessageInfo

func (m *StatusResponse_Result_TmStatus_ValidatorInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo) GetPubKey() *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

type StatusResponse_Result_TmStatus_ValidatorInfo_PubKey struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) Reset() {
	*m = StatusResponse_Result_TmStatus_ValidatorInfo_PubKey{}
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) String() string {
	return proto.CompactTextString(m)
}
func (*StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) ProtoMessage() {}
func (*StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2, 0, 0, 1, 0}
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo_PubKey.Unmarshal(m, b)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo_PubKey.Marshal(b, m, deterministic)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo_PubKey.Merge(m, src)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo_PubKey.Size(m)
}
func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Result_TmStatus_ValidatorInfo_PubKey proto.InternalMessageInfo

func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StatusResponse_Result_TmStatus_ValidatorInfo_PubKey) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GenesisResponse struct {
	Jsonrpc              string                  `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id                   string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result               *GenesisResponse_Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GenesisResponse) Reset()         { *m = GenesisResponse{} }
func (m *GenesisResponse) String() string { return proto.CompactTextString(m) }
func (*GenesisResponse) ProtoMessage()    {}
func (*GenesisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3}
}

func (m *GenesisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse.Unmarshal(m, b)
}
func (m *GenesisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse.Marshal(b, m, deterministic)
}
func (m *GenesisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse.Merge(m, src)
}
func (m *GenesisResponse) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse.Size(m)
}
func (m *GenesisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse proto.InternalMessageInfo

func (m *GenesisResponse) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *GenesisResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenesisResponse) GetResult() *GenesisResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GenesisResponse_Result struct {
	Genesis              *GenesisResponse_Result_Genesis `protobuf:"bytes,1,opt,name=genesis,proto3" json:"genesis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GenesisResponse_Result) Reset()         { *m = GenesisResponse_Result{} }
func (m *GenesisResponse_Result) String() string { return proto.CompactTextString(m) }
func (*GenesisResponse_Result) ProtoMessage()    {}
func (*GenesisResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0}
}

func (m *GenesisResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result.Unmarshal(m, b)
}
func (m *GenesisResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result.Merge(m, src)
}
func (m *GenesisResponse_Result) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result.Size(m)
}
func (m *GenesisResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result proto.InternalMessageInfo

func (m *GenesisResponse_Result) GetGenesis() *GenesisResponse_Result_Genesis {
	if m != nil {
		return m.Genesis
	}
	return nil
}

type GenesisResponse_Result_Genesis struct {
	GenesisTime          string                                          `protobuf:"bytes,1,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	ChainId              string                                          `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ConsensusParams      *GenesisResponse_Result_Genesis_ConsensusParams `protobuf:"bytes,3,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params,omitempty"`
	AppHash              string                                          `protobuf:"bytes,4,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	AppState             *GenesisResponse_Result_Genesis_AppState        `protobuf:"bytes,5,opt,name=app_state,json=appState,proto3" json:"app_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *GenesisResponse_Result_Genesis) Reset()         { *m = GenesisResponse_Result_Genesis{} }
func (m *GenesisResponse_Result_Genesis) String() string { return proto.CompactTextString(m) }
func (*GenesisResponse_Result_Genesis) ProtoMessage()    {}
func (*GenesisResponse_Result_Genesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0}
}

func (m *GenesisResponse_Result_Genesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis.Size(m)
}
func (m *GenesisResponse_Result_Genesis) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis) GetGenesisTime() string {
	if m != nil {
		return m.GenesisTime
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis) GetConsensusParams() *GenesisResponse_Result_Genesis_ConsensusParams {
	if m != nil {
		return m.ConsensusParams
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis) GetAppHash() string {
	if m != nil {
		return m.AppHash
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis) GetAppState() *GenesisResponse_Result_Genesis_AppState {
	if m != nil {
		return m.AppState
	}
	return nil
}

type GenesisResponse_Result_Genesis_ConsensusParams struct {
	Block                *GenesisResponse_Result_Genesis_ConsensusParams_Block     `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Evidence             *GenesisResponse_Result_Genesis_ConsensusParams_Evidence  `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Validator            *GenesisResponse_Result_Genesis_ConsensusParams_Validator `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams) Reset() {
	*m = GenesisResponse_Result_Genesis_ConsensusParams{}
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_ConsensusParams) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_ConsensusParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 0}
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams.Size(m)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_ConsensusParams) GetBlock() *GenesisResponse_Result_Genesis_ConsensusParams_Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams) GetEvidence() *GenesisResponse_Result_Genesis_ConsensusParams_Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams) GetValidator() *GenesisResponse_Result_Genesis_ConsensusParams_Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

type GenesisResponse_Result_Genesis_ConsensusParams_Block struct {
	MaxBytes             string   `protobuf:"bytes,1,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxGas               string   `protobuf:"bytes,2,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
	TimeIotaMs           string   `protobuf:"bytes,3,opt,name=time_iota_ms,json=timeIotaMs,proto3" json:"time_iota_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) Reset() {
	*m = GenesisResponse_Result_Genesis_ConsensusParams_Block{}
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_ConsensusParams_Block) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_ConsensusParams_Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 0, 0}
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Block.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Block.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Block.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Block.Size(m)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Block.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Block proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) GetMaxBytes() string {
	if m != nil {
		return m.MaxBytes
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) GetMaxGas() string {
	if m != nil {
		return m.MaxGas
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Block) GetTimeIotaMs() string {
	if m != nil {
		return m.TimeIotaMs
	}
	return ""
}

type GenesisResponse_Result_Genesis_ConsensusParams_Evidence struct {
	MaxAge               string   `protobuf:"bytes,1,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) Reset() {
	*m = GenesisResponse_Result_Genesis_ConsensusParams_Evidence{}
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_ConsensusParams_Evidence) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_ConsensusParams_Evidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 0, 1}
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Evidence.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Evidence.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Evidence.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Evidence.Size(m)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Evidence.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Evidence proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Evidence) GetMaxAge() string {
	if m != nil {
		return m.MaxAge
	}
	return ""
}

type GenesisResponse_Result_Genesis_ConsensusParams_Validator struct {
	PubKeyTypes          []string `protobuf:"bytes,1,rep,name=pub_key_types,json=pubKeyTypes,proto3" json:"pub_key_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) Reset() {
	*m = GenesisResponse_Result_Genesis_ConsensusParams_Validator{}
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_ConsensusParams_Validator) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_ConsensusParams_Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 0, 2}
}

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Validator.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Validator.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Validator.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Validator.Size(m)
}
func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_ConsensusParams_Validator proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_ConsensusParams_Validator) GetPubKeyTypes() []string {
	if m != nil {
		return m.PubKeyTypes
	}
	return nil
}

type GenesisResponse_Result_Genesis_AppState struct {
	StartHeight          string                                                `protobuf:"bytes,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	Validators           []*GenesisResponse_Result_Genesis_AppState_Validator  `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
	Candidates           []*GenesisResponse_Result_Genesis_AppState_Candidates `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Accounts             []*GenesisResponse_Result_Genesis_AppState_Account    `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	MaxGas               string                                                `protobuf:"bytes,5,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
	TotalSlashed         string                                                `protobuf:"bytes,6,opt,name=total_slashed,json=totalSlashed,proto3" json:"total_slashed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_AppState) Reset() {
	*m = GenesisResponse_Result_Genesis_AppState{}
}
func (m *GenesisResponse_Result_Genesis_AppState) String() string { return proto.CompactTextString(m) }
func (*GenesisResponse_Result_Genesis_AppState) ProtoMessage()    {}
func (*GenesisResponse_Result_Genesis_AppState) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 1}
}

func (m *GenesisResponse_Result_Genesis_AppState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_AppState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_AppState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_AppState) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState.Size(m)
}
func (m *GenesisResponse_Result_Genesis_AppState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_AppState proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_AppState) GetStartHeight() string {
	if m != nil {
		return m.StartHeight
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState) GetValidators() []*GenesisResponse_Result_Genesis_AppState_Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_AppState) GetCandidates() []*GenesisResponse_Result_Genesis_AppState_Candidates {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_AppState) GetAccounts() []*GenesisResponse_Result_Genesis_AppState_Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_AppState) GetMaxGas() string {
	if m != nil {
		return m.MaxGas
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState) GetTotalSlashed() string {
	if m != nil {
		return m.TotalSlashed
	}
	return ""
}

type GenesisResponse_Result_Genesis_AppState_Validator struct {
	RewardAddress        string   `protobuf:"bytes,1,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
	TotalBipStake        string   `protobuf:"bytes,2,opt,name=total_bip_stake,json=totalBipStake,proto3" json:"total_bip_stake,omitempty"`
	PubKey               string   `protobuf:"bytes,3,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Commission           string   `protobuf:"bytes,4,opt,name=commission,proto3" json:"commission,omitempty"`
	AccumReward          string   `protobuf:"bytes,5,opt,name=accum_reward,json=accumReward,proto3" json:"accum_reward,omitempty"`
	AbsentTimes          string   `protobuf:"bytes,6,opt,name=absent_times,json=absentTimes,proto3" json:"absent_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) Reset() {
	*m = GenesisResponse_Result_Genesis_AppState_Validator{}
}
func (m *GenesisResponse_Result_Genesis_AppState_Validator) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_AppState_Validator) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_AppState_Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 1, 0}
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Validator.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_AppState_Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Validator.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_AppState_Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Validator.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_AppState_Validator) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Validator.Size(m)
}
func (m *GenesisResponse_Result_Genesis_AppState_Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Validator proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_AppState_Validator) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) GetTotalBipStake() string {
	if m != nil {
		return m.TotalBipStake
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) GetCommission() string {
	if m != nil {
		return m.Commission
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) GetAccumReward() string {
	if m != nil {
		return m.AccumReward
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Validator) GetAbsentTimes() string {
	if m != nil {
		return m.AbsentTimes
	}
	return ""
}

type GenesisResponse_Result_Genesis_AppState_Candidates struct {
	RewardAddress        string                                                      `protobuf:"bytes,1,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
	OwnerAddress         string                                                      `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	TotalBipStake        string                                                      `protobuf:"bytes,3,opt,name=total_bip_stake,json=totalBipStake,proto3" json:"total_bip_stake,omitempty"`
	PubKey               string                                                      `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Commission           string                                                      `protobuf:"bytes,5,opt,name=commission,proto3" json:"commission,omitempty"`
	Stakes               []*GenesisResponse_Result_Genesis_AppState_Candidates_Stake `protobuf:"bytes,6,rep,name=stakes,proto3" json:"stakes,omitempty"`
	CreatedAtBlock       string                                                      `protobuf:"bytes,7,opt,name=created_at_block,json=createdAtBlock,proto3" json:"created_at_block,omitempty"`
	Status               float64                                                     `protobuf:"fixed64,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                    `json:"-"`
	XXX_unrecognized     []byte                                                      `json:"-"`
	XXX_sizecache        int32                                                       `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) Reset() {
	*m = GenesisResponse_Result_Genesis_AppState_Candidates{}
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_AppState_Candidates) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_AppState_Candidates) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 1, 1}
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates.Size(m)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetTotalBipStake() string {
	if m != nil {
		return m.TotalBipStake
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetCommission() string {
	if m != nil {
		return m.Commission
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetStakes() []*GenesisResponse_Result_Genesis_AppState_Candidates_Stake {
	if m != nil {
		return m.Stakes
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetCreatedAtBlock() string {
	if m != nil {
		return m.CreatedAtBlock
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates) GetStatus() float64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GenesisResponse_Result_Genesis_AppState_Candidates_Stake struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Coin                 string   `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	BipValue             string   `protobuf:"bytes,4,opt,name=bip_value,json=bipValue,proto3" json:"bip_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) Reset() {
	*m = GenesisResponse_Result_Genesis_AppState_Candidates_Stake{}
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_AppState_Candidates_Stake) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_AppState_Candidates_Stake) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 1, 1, 0}
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates_Stake.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates_Stake.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates_Stake.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates_Stake.Size(m)
}
func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates_Stake.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Candidates_Stake proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Candidates_Stake) GetBipValue() string {
	if m != nil {
		return m.BipValue
	}
	return ""
}

type GenesisResponse_Result_Genesis_AppState_Account struct {
	Address              string                                                     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              []*GenesisResponse_Result_Genesis_AppState_Account_Balance `protobuf:"bytes,2,rep,name=balance,proto3" json:"balance,omitempty"`
	Nonce                string                                                     `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_AppState_Account) Reset() {
	*m = GenesisResponse_Result_Genesis_AppState_Account{}
}
func (m *GenesisResponse_Result_Genesis_AppState_Account) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_AppState_Account) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_AppState_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 1, 2}
}

func (m *GenesisResponse_Result_Genesis_AppState_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account.Size(m)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_AppState_Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Account) GetBalance() []*GenesisResponse_Result_Genesis_AppState_Account_Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *GenesisResponse_Result_Genesis_AppState_Account) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type GenesisResponse_Result_Genesis_AppState_Account_Balance struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) Reset() {
	*m = GenesisResponse_Result_Genesis_AppState_Account_Balance{}
}
func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) String() string {
	return proto.CompactTextString(m)
}
func (*GenesisResponse_Result_Genesis_AppState_Account_Balance) ProtoMessage() {}
func (*GenesisResponse_Result_Genesis_AppState_Account_Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{3, 0, 0, 1, 2, 0}
}

func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account_Balance.Unmarshal(m, b)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account_Balance.Marshal(b, m, deterministic)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account_Balance.Merge(m, src)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) XXX_Size() int {
	return xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account_Balance.Size(m)
}
func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisResponse_Result_Genesis_AppState_Account_Balance proto.InternalMessageInfo

func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *GenesisResponse_Result_Genesis_AppState_Account_Balance) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MinGasPriceResponse struct {
	Jsonrpc              string   `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinGasPriceResponse) Reset()         { *m = MinGasPriceResponse{} }
func (m *MinGasPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MinGasPriceResponse) ProtoMessage()    {}
func (*MinGasPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{4}
}

func (m *MinGasPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinGasPriceResponse.Unmarshal(m, b)
}
func (m *MinGasPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinGasPriceResponse.Marshal(b, m, deterministic)
}
func (m *MinGasPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinGasPriceResponse.Merge(m, src)
}
func (m *MinGasPriceResponse) XXX_Size() int {
	return xxx_messageInfo_MinGasPriceResponse.Size(m)
}
func (m *MinGasPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MinGasPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MinGasPriceResponse proto.InternalMessageInfo

func (m *MinGasPriceResponse) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *MinGasPriceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MinGasPriceResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "pb.NodeInfo")
	proto.RegisterType((*NodeInfo_ProtocolVersion)(nil), "pb.NodeInfo.ProtocolVersion")
	proto.RegisterType((*NodeInfo_Other)(nil), "pb.NodeInfo.Other")
	proto.RegisterType((*NetInfoResponse)(nil), "pb.NetInfoResponse")
	proto.RegisterType((*NetInfoResponse_Result)(nil), "pb.NetInfoResponse.Result")
	proto.RegisterType((*NetInfoResponse_Result_Peer)(nil), "pb.NetInfoResponse.Result.Peer")
	proto.RegisterType((*NetInfoResponse_Result_Peer_ConnectionStatus)(nil), "pb.NetInfoResponse.Result.Peer.ConnectionStatus")
	proto.RegisterType((*NetInfoResponse_Result_Peer_ConnectionStatus_Monitor)(nil), "pb.NetInfoResponse.Result.Peer.ConnectionStatus.Monitor")
	proto.RegisterType((*NetInfoResponse_Result_Peer_ConnectionStatus_Channel)(nil), "pb.NetInfoResponse.Result.Peer.ConnectionStatus.Channel")
	proto.RegisterType((*StatusResponse)(nil), "pb.StatusResponse")
	proto.RegisterType((*StatusResponse_Result)(nil), "pb.StatusResponse.Result")
	proto.RegisterType((*StatusResponse_Result_TmStatus)(nil), "pb.StatusResponse.Result.TmStatus")
	proto.RegisterType((*StatusResponse_Result_TmStatus_SyncInfo)(nil), "pb.StatusResponse.Result.TmStatus.SyncInfo")
	proto.RegisterType((*StatusResponse_Result_TmStatus_ValidatorInfo)(nil), "pb.StatusResponse.Result.TmStatus.ValidatorInfo")
	proto.RegisterType((*StatusResponse_Result_TmStatus_ValidatorInfo_PubKey)(nil), "pb.StatusResponse.Result.TmStatus.ValidatorInfo.PubKey")
	proto.RegisterType((*GenesisResponse)(nil), "pb.GenesisResponse")
	proto.RegisterType((*GenesisResponse_Result)(nil), "pb.GenesisResponse.Result")
	proto.RegisterType((*GenesisResponse_Result_Genesis)(nil), "pb.GenesisResponse.Result.Genesis")
	proto.RegisterType((*GenesisResponse_Result_Genesis_ConsensusParams)(nil), "pb.GenesisResponse.Result.Genesis.ConsensusParams")
	proto.RegisterType((*GenesisResponse_Result_Genesis_ConsensusParams_Block)(nil), "pb.GenesisResponse.Result.Genesis.ConsensusParams.Block")
	proto.RegisterType((*GenesisResponse_Result_Genesis_ConsensusParams_Evidence)(nil), "pb.GenesisResponse.Result.Genesis.ConsensusParams.Evidence")
	proto.RegisterType((*GenesisResponse_Result_Genesis_ConsensusParams_Validator)(nil), "pb.GenesisResponse.Result.Genesis.ConsensusParams.Validator")
	proto.RegisterType((*GenesisResponse_Result_Genesis_AppState)(nil), "pb.GenesisResponse.Result.Genesis.AppState")
	proto.RegisterType((*GenesisResponse_Result_Genesis_AppState_Validator)(nil), "pb.GenesisResponse.Result.Genesis.AppState.Validator")
	proto.RegisterType((*GenesisResponse_Result_Genesis_AppState_Candidates)(nil), "pb.GenesisResponse.Result.Genesis.AppState.Candidates")
	proto.RegisterType((*GenesisResponse_Result_Genesis_AppState_Candidates_Stake)(nil), "pb.GenesisResponse.Result.Genesis.AppState.Candidates.Stake")
	proto.RegisterType((*GenesisResponse_Result_Genesis_AppState_Account)(nil), "pb.GenesisResponse.Result.Genesis.AppState.Account")
	proto.RegisterType((*GenesisResponse_Result_Genesis_AppState_Account_Balance)(nil), "pb.GenesisResponse.Result.Genesis.AppState.Account.Balance")
	proto.RegisterType((*MinGasPriceResponse)(nil), "pb.MinGasPriceResponse")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_11b04836674e6f94) }

var fileDescriptor_11b04836674e6f94 = []byte{
	// 1971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcf, 0x6f, 0x1b, 0x4f,
	0x15, 0x97, 0xbd, 0xb1, 0xbd, 0x7e, 0x8e, 0xe3, 0x64, 0x8a, 0x5a, 0x77, 0xbf, 0x15, 0x0d, 0x2e,
	0xa0, 0xf0, 0x43, 0x0e, 0xb8, 0xfa, 0x02, 0x12, 0x5f, 0x09, 0xa5, 0x69, 0xd5, 0x58, 0x5f, 0xda,
	0x86, 0x71, 0x9a, 0x4a, 0x5f, 0x09, 0xad, 0xc6, 0xeb, 0xa9, 0xb3, 0xc4, 0x9e, 0x1d, 0xed, 0x8c,
	0xdd, 0x98, 0x23, 0x57, 0x8e, 0x88, 0x2b, 0x57, 0x24, 0x04, 0x67, 0x0e, 0x9c, 0x90, 0xe0, 0x80,
	0x10, 0x17, 0x10, 0x07, 0xc4, 0x0d, 0xf1, 0x07, 0xf0, 0x27, 0xa0, 0x37, 0x33, 0xbb, 0x59, 0xbb,
	0x49, 0x53, 0x17, 0x4e, 0xd9, 0xf7, 0x79, 0x33, 0x1f, 0xbf, 0x5f, 0xf3, 0xe6, 0x4d, 0x00, 0xce,
	0xb4, 0x96, 0x5d, 0x99, 0x26, 0x3a, 0x21, 0x65, 0x39, 0x0c, 0xee, 0x8d, 0x93, 0x64, 0x3c, 0xe1,
	0xfb, 0x4c, 0xc6, 0xfb, 0x4c, 0x88, 0x44, 0x33, 0x1d, 0x27, 0x42, 0xd9, 0x15, 0xc1, 0x47, 0x4e,
	0x6b, 0xa4, 0xe1, 0xec, 0xf5, 0x3e, 0x9f, 0x4a, 0xbd, 0xb0, 0xca, 0xce, 0xaf, 0x3c, 0xf0, 0x9f,
	0x27, 0x23, 0xde, 0x17, 0xaf, 0x13, 0xf2, 0x14, 0xb6, 0x0d, 0x1a, 0x25, 0x93, 0x70, 0xce, 0x53,
	0x15, 0x27, 0xa2, 0xed, 0xef, 0x96, 0xf6, 0x1a, 0xbd, 0x7b, 0x5d, 0x39, 0xec, 0x66, 0xeb, 0xba,
	0xc7, 0x6e, 0xd1, 0xa9, 0x5d, 0x43, 0x5b, 0x72, 0x19, 0x20, 0x5b, 0x50, 0x8e, 0x47, 0xed, 0xd2,
	0x6e, 0x69, 0xaf, 0x4e, 0xcb, 0xf1, 0x88, 0xdc, 0x87, 0xc6, 0x24, 0x56, 0x9a, 0x8b, 0x90, 0x8d,
	0x46, 0x69, 0xbb, 0x6c, 0x14, 0x60, 0xa1, 0x83, 0xd1, 0x28, 0x25, 0x6d, 0xa8, 0x09, 0xae, 0xdf,
	0x24, 0xe9, 0x79, 0xdb, 0x33, 0xca, 0x4c, 0x44, 0x4d, 0x66, 0xca, 0x86, 0xd5, 0x38, 0x91, 0x04,
	0xe0, 0x47, 0x67, 0x4c, 0x08, 0x3e, 0x51, 0xed, 0x8a, 0x51, 0xe5, 0x32, 0xee, 0x9a, 0x26, 0x22,
	0x3e, 0xe7, 0x69, 0xbb, 0x6a, 0x77, 0x39, 0x91, 0xec, 0x41, 0x25, 0xd1, 0x67, 0x3c, 0x6d, 0xd7,
	0x8c, 0x63, 0x64, 0xc9, 0xb1, 0x17, 0xa8, 0xa1, 0x76, 0x41, 0xf0, 0x29, 0xb4, 0x56, 0x1c, 0x25,
	0xdb, 0xe0, 0xc9, 0x9e, 0x34, 0x26, 0x6e, 0x50, 0xfc, 0x24, 0x9f, 0x83, 0xca, 0x70, 0x92, 0x44,
	0xe7, 0xc6, 0xd9, 0x0d, 0x6a, 0x05, 0x5c, 0xc7, 0xa4, 0x34, 0x7e, 0x6e, 0x50, 0xfc, 0x0c, 0x0e,
	0xa1, 0x62, 0xc8, 0xc9, 0x5d, 0xf0, 0xf5, 0x45, 0x18, 0x8b, 0x11, 0xbf, 0x70, 0x71, 0xa8, 0xe9,
	0x8b, 0x3e, 0x8a, 0x18, 0xa5, 0x54, 0x46, 0x26, 0x44, 0x5c, 0x29, 0x17, 0x3e, 0x48, 0x65, 0x74,
	0x60, 0x91, 0xce, 0x2f, 0x00, 0x5a, 0xcf, 0xb9, 0x46, 0x53, 0x29, 0x57, 0x32, 0x11, 0x8a, 0xa3,
	0xa7, 0x3f, 0x52, 0x89, 0x48, 0x65, 0xe4, 0x36, 0x64, 0xa2, 0x4b, 0x42, 0x39, 0x4f, 0x42, 0x0f,
	0xaa, 0x29, 0x57, 0xb3, 0x89, 0x36, 0xf6, 0x37, 0x7a, 0x81, 0x71, 0x7d, 0x99, 0xae, 0x4b, 0xcd,
	0x0a, 0xea, 0x56, 0x06, 0xbf, 0xae, 0x43, 0xd5, 0x42, 0xe4, 0x1e, 0xd4, 0x6d, 0xc2, 0x62, 0x31,
	0x36, 0xa9, 0xf0, 0xe9, 0x25, 0x70, 0xa9, 0xe5, 0x29, 0x5a, 0xee, 0xed, 0xd5, 0xe9, 0x25, 0x40,
	0xee, 0x40, 0x4d, 0x84, 0x92, 0xa3, 0x0e, 0xed, 0xf1, 0x68, 0x55, 0x1c, 0xa3, 0x44, 0x3e, 0x86,
	0x8a, 0x85, 0xbd, 0x5d, 0x6f, 0xaf, 0xd1, 0xbb, 0x7f, 0xbd, 0x49, 0x5d, 0xdc, 0x40, 0xed, 0xea,
	0xe0, 0xe7, 0x3e, 0x6c, 0xa0, 0x4c, 0xbe, 0x02, 0x75, 0x91, 0x8c, 0x78, 0x18, 0x8b, 0xd7, 0x89,
	0x31, 0xaa, 0xd1, 0xdb, 0x2c, 0x66, 0x94, 0xfa, 0x22, 0x2b, 0xee, 0xfb, 0xd0, 0x88, 0x55, 0x98,
	0xcc, 0xf4, 0x30, 0x99, 0x09, 0x5b, 0x9c, 0x3e, 0x85, 0x58, 0xbd, 0x70, 0x08, 0xf9, 0x21, 0xec,
	0x44, 0x89, 0x10, 0x3c, 0xc2, 0xc3, 0x13, 0x2a, 0xcd, 0xf4, 0xcc, 0x9a, 0xdb, 0xe8, 0x7d, 0xe3,
	0x06, 0xbb, 0xba, 0x87, 0xf9, 0xc6, 0x81, 0xd9, 0x47, 0xb7, 0xa3, 0x15, 0x84, 0x7c, 0x04, 0xf5,
	0x94, 0x4f, 0x13, 0xcd, 0xc3, 0x58, 0xba, 0x22, 0xf7, 0x2d, 0xd0, 0x97, 0xc1, 0x1f, 0xaa, 0xb0,
	0xbd, 0xca, 0x81, 0x05, 0xfe, 0x78, 0x96, 0x9a, 0xb3, 0x6c, 0x7c, 0xf3, 0x68, 0x2e, 0x93, 0xcf,
	0xa0, 0x31, 0xe0, 0x62, 0xf4, 0x2c, 0x11, 0xb1, 0x4e, 0x52, 0xe3, 0x4d, 0xa3, 0xf7, 0x9d, 0x75,
	0xcd, 0xec, 0xba, 0xfd, 0xb4, 0x48, 0x86, 0xdc, 0x94, 0x47, 0xf3, 0x8c, 0xbb, 0xfc, 0xbf, 0x72,
	0x17, 0xc8, 0xc8, 0x09, 0xf8, 0x87, 0xd9, 0xa1, 0xb5, 0x39, 0x5f, 0x9f, 0xd8, 0x11, 0xd0, 0x9c,
	0x29, 0xf8, 0x7b, 0x19, 0x6a, 0xd9, 0x2f, 0xdc, 0x86, 0xea, 0x41, 0xa4, 0xe3, 0x39, 0x6f, 0x37,
	0x4d, 0x8a, 0x9d, 0x84, 0x27, 0x75, 0xa0, 0x59, 0xaa, 0xdd, 0x31, 0xb1, 0xc2, 0x52, 0x8c, 0xcb,
	0x2b, 0x31, 0x26, 0xb0, 0xd1, 0x1f, 0x4d, 0xb8, 0x49, 0x96, 0x47, 0xcd, 0x37, 0xb2, 0x3c, 0x5a,
	0x68, 0xae, 0x5c, 0x42, 0xac, 0x80, 0x87, 0x70, 0xc0, 0xa6, 0x72, 0xc2, 0x6d, 0x27, 0xf2, 0x68,
	0x26, 0x22, 0x7f, 0x5f, 0x28, 0x4d, 0x99, 0xe6, 0xa6, 0x13, 0x79, 0x34, 0x97, 0x71, 0xd7, 0xe1,
	0x2c, 0x35, 0xaa, 0x9a, 0xdd, 0xe5, 0x44, 0xd4, 0x1c, 0xcc, 0xc7, 0x46, 0xe3, 0x5b, 0x8d, 0x13,
	0x91, 0xef, 0x98, 0xb3, 0x73, 0xa3, 0xaa, 0x5b, 0xbe, 0x4c, 0x46, 0x9d, 0x31, 0x87, 0xf2, 0x69,
	0x1b, 0xac, 0x2e, 0x93, 0x91, 0xf1, 0x24, 0x9e, 0x72, 0x54, 0x35, 0x2c, 0xa3, 0x13, 0x0d, 0x63,
	0x9a, 0x8c, 0x4d, 0xcb, 0xd9, 0xdc, 0x2d, 0xed, 0x35, 0x69, 0x2e, 0x07, 0xbf, 0x29, 0x41, 0xcd,
	0x05, 0x19, 0xdb, 0x49, 0xff, 0xb1, 0x71, 0xaf, 0x42, 0xcb, 0xfd, 0xc7, 0xe4, 0xeb, 0xb0, 0x83,
	0x45, 0xf3, 0x83, 0x19, 0x9f, 0xf1, 0x43, 0x26, 0x59, 0x14, 0xeb, 0x85, 0x89, 0xad, 0x47, 0xdf,
	0x56, 0x90, 0x2f, 0x42, 0x33, 0x07, 0x07, 0xf1, 0x8f, 0xb9, 0x0b, 0xf6, 0x32, 0x68, 0x6d, 0x89,
	0x93, 0x14, 0xa9, 0x3c, 0xe7, 0x9d, 0x93, 0x49, 0x07, 0x36, 0x29, 0x8f, 0xb8, 0xd0, 0x93, 0xc5,
	0x80, 0x0b, 0xed, 0x12, 0xb0, 0x84, 0x75, 0x7e, 0xe7, 0xc3, 0x96, 0x3b, 0x80, 0xeb, 0xf7, 0xc7,
	0x6f, 0xae, 0xf4, 0xc7, 0xbb, 0x58, 0x98, 0xcb, 0x6c, 0xab, 0xed, 0xf1, 0xcf, 0xb5, 0xbc, 0x3d,
	0x16, 0xee, 0xa9, 0xda, 0xf2, 0x3d, 0xf5, 0x55, 0xd8, 0x99, 0x30, 0xcd, 0x95, 0x0e, 0xcd, 0xe5,
	0x10, 0x9e, 0x31, 0x75, 0xe6, 0x6c, 0x69, 0x59, 0xc5, 0x23, 0xc4, 0x8f, 0x98, 0x3a, 0x23, 0x5f,
	0x06, 0x07, 0x85, 0x4c, 0x4a, 0xbb, 0xd2, 0x1a, 0xd8, 0xb4, 0xf0, 0x81, 0x94, 0x66, 0x5d, 0x17,
	0x6e, 0x2d, 0x73, 0xf2, 0x78, 0x7c, 0xa6, 0x5d, 0xcc, 0x76, 0x8a, 0xac, 0x46, 0xf1, 0x96, 0x0d,
	0x3a, 0x9e, 0x72, 0x77, 0x9f, 0x16, 0x6d, 0xc0, 0x9a, 0x20, 0x7b, 0xb0, 0x7d, 0xce, 0xb9, 0x0c,
	0x27, 0x4c, 0x69, 0xd3, 0x06, 0xf3, 0xaa, 0xde, 0x42, 0xfc, 0xfb, 0x4c, 0xe9, 0x81, 0x41, 0xc9,
	0xf7, 0xa0, 0xae, 0xa7, 0x59, 0xa7, 0xac, 0x9a, 0xa0, 0x75, 0xae, 0x0d, 0x5a, 0xf7, 0x64, 0xea,
	0x70, 0x5f, 0xbb, 0xaf, 0xe0, 0xa7, 0x15, 0xf0, 0x33, 0x78, 0xb9, 0x97, 0x7b, 0xef, 0xec, 0xe5,
	0x47, 0x50, 0x57, 0x0b, 0x11, 0xd9, 0xa5, 0xb6, 0xf7, 0x7d, 0xed, 0xe6, 0x1f, 0xee, 0x0e, 0x16,
	0x22, 0xb2, 0x4c, 0xca, 0x7d, 0x91, 0x57, 0xb0, 0x35, 0x67, 0x93, 0x78, 0xc4, 0x74, 0x92, 0x5a,
	0xba, 0x42, 0xc7, 0xbf, 0x81, 0xee, 0x34, 0xdb, 0x68, 0x38, 0x9b, 0xf3, 0xa2, 0x18, 0xfc, 0xb3,
	0x04, 0x7e, 0xf6, 0x7b, 0x57, 0x97, 0x40, 0xe5, 0xbd, 0x4b, 0xa0, 0xb4, 0x46, 0x09, 0x94, 0xd7,
	0x2a, 0x01, 0xef, 0xea, 0x12, 0xb8, 0x0f, 0x8d, 0x88, 0xe9, 0xe8, 0x2c, 0x16, 0xe3, 0x70, 0x26,
	0xdd, 0x6d, 0x0f, 0x19, 0xf4, 0x52, 0x06, 0x7f, 0x2d, 0x41, 0x73, 0xc9, 0x7d, 0xac, 0xff, 0x6c,
	0x70, 0x71, 0x13, 0x9c, 0x13, 0xc9, 0x31, 0xd4, 0xe4, 0x6c, 0x18, 0x9e, 0xf3, 0x85, 0x4b, 0xd5,
	0xb7, 0xd7, 0x8d, 0x6d, 0xf7, 0x78, 0x36, 0xfc, 0x94, 0x2f, 0x68, 0x55, 0x9a, 0xbf, 0xe4, 0x0b,
	0xb0, 0x39, 0x4f, 0x34, 0x1a, 0x27, 0x93, 0x37, 0x3c, 0x75, 0x3e, 0x37, 0x2c, 0x76, 0x8c, 0x50,
	0xd0, 0x83, 0xaa, 0xdd, 0x84, 0x5d, 0x5c, 0x2f, 0x24, 0x77, 0xe7, 0xc8, 0x7c, 0x63, 0x17, 0x9f,
	0xb3, 0xc9, 0x8c, 0x67, 0x77, 0x81, 0x11, 0x3a, 0xff, 0xda, 0x86, 0xd6, 0x53, 0x2e, 0xb8, 0x8a,
	0xd5, 0xff, 0x6b, 0xbc, 0x5a, 0xa1, 0x5b, 0xed, 0x1f, 0xff, 0x69, 0xe5, 0xfd, 0xe3, 0x13, 0xa8,
	0x8d, 0xed, 0x62, 0x17, 0xa5, 0xce, 0xf5, 0xfb, 0x73, 0x38, 0xdb, 0x12, 0xfc, 0xb2, 0x05, 0x35,
	0x07, 0x62, 0x74, 0x1c, 0x6c, 0x73, 0x6c, 0xed, 0x6e, 0x38, 0xcc, 0xe4, 0xf7, 0xae, 0x19, 0x9d,
	0x63, 0x11, 0xe6, 0x1e, 0xd4, 0x8c, 0xdc, 0xc7, 0x29, 0x08, 0x47, 0x17, 0xc5, 0x85, 0x9a, 0xa9,
	0x50, 0xb2, 0x94, 0x4d, 0x95, 0x73, 0xa8, 0x77, 0xb3, 0x41, 0x78, 0x57, 0xdb, 0xad, 0xc7, 0x66,
	0x27, 0x6d, 0x45, 0xcb, 0x00, 0xfe, 0x72, 0x5e, 0xd6, 0x6e, 0x9e, 0x67, 0xae, 0xa0, 0x8f, 0xa0,
	0x8e, 0x2a, 0xd3, 0x71, 0xcc, 0xe1, 0x70, 0x87, 0xfa, 0x86, 0x9f, 0x3c, 0x90, 0xd2, 0xb4, 0x23,
	0x8a, 0xc4, 0xe6, 0x2b, 0xf8, 0x8b, 0x07, 0xad, 0x15, 0x4b, 0xc8, 0xf3, 0xe2, 0xa0, 0xee, 0xa6,
	0x8e, 0xf5, 0x9c, 0xe9, 0x9a, 0xf3, 0x91, 0x8d, 0xf8, 0xaf, 0xc0, 0xe7, 0xf3, 0x78, 0xc4, 0x45,
	0xc4, 0x5d, 0xcb, 0xf8, 0xee, 0x07, 0x50, 0x3e, 0x71, 0x14, 0x34, 0x27, 0x23, 0x9f, 0x41, 0x3d,
	0xef, 0x24, 0x2e, 0xf2, 0x9f, 0x7c, 0x00, 0x73, 0x7e, 0x80, 0xe8, 0x25, 0x5d, 0x10, 0x42, 0xc5,
	0x38, 0x81, 0xc3, 0xe8, 0x94, 0x5d, 0x84, 0x43, 0x33, 0xca, 0xd8, 0x02, 0xf1, 0xa7, 0xec, 0xc2,
	0x4e, 0x33, 0x77, 0xa0, 0x86, 0xca, 0x31, 0x53, 0xae, 0x38, 0xaa, 0x53, 0x76, 0xf1, 0x94, 0x29,
	0xb2, 0x0b, 0x9b, 0x58, 0x51, 0x61, 0x9c, 0x68, 0x16, 0x4e, 0xb3, 0x83, 0x0e, 0x88, 0xf5, 0x13,
	0xcd, 0x9e, 0xa9, 0xe0, 0x01, 0xf8, 0x99, 0x4b, 0x19, 0x0d, 0x1b, 0x67, 0x25, 0x88, 0x34, 0x07,
	0x63, 0x1e, 0xec, 0x43, 0x3d, 0xb7, 0x8e, 0x74, 0xa0, 0xe9, 0xba, 0x43, 0x88, 0x47, 0x33, 0x7b,
	0x3c, 0x34, 0xec, 0x51, 0x3f, 0x41, 0x28, 0xf8, 0x53, 0x1d, 0xfc, 0x2c, 0xcd, 0x58, 0xde, 0x0a,
	0x47, 0xb7, 0xac, 0xe1, 0xb9, 0xf2, 0x36, 0x98, 0x6b, 0x75, 0x2f, 0x01, 0x72, 0x9f, 0xd1, 0x07,
	0x1c, 0x33, 0x3f, 0x5e, 0xa3, 0x94, 0x0a, 0xc1, 0x2b, 0x10, 0x91, 0x53, 0x80, 0x88, 0x89, 0x11,
	0x8a, 0x3c, 0x9b, 0x5e, 0xbf, 0xb5, 0x0e, 0xed, 0x61, 0xbe, 0x9b, 0x16, 0x98, 0xc8, 0x0b, 0xf0,
	0x59, 0x14, 0x25, 0x33, 0xa1, 0x71, 0xac, 0x44, 0xd6, 0x87, 0xeb, 0xb0, 0x1e, 0xd8, 0xbd, 0x34,
	0x27, 0x29, 0x26, 0xb0, 0xb2, 0x94, 0xc0, 0x07, 0xd0, 0xd4, 0x89, 0x66, 0x93, 0x50, 0x4d, 0x98,
	0x3a, 0xe3, 0x23, 0xf7, 0x38, 0xde, 0x34, 0xe0, 0xc0, 0x62, 0xc1, 0x3f, 0x4a, 0xc5, 0xfc, 0x7c,
	0x09, 0xb6, 0x52, 0xfe, 0x86, 0xa5, 0xa3, 0x95, 0x77, 0x69, 0xd3, 0xa2, 0xee, 0x69, 0x8a, 0xb7,
	0x96, 0x65, 0x1e, 0xc6, 0xe6, 0x08, 0x9f, 0x67, 0x0d, 0xd7, 0xfe, 0xe0, 0xa3, 0x18, 0x8d, 0x3d,
	0x37, 0x45, 0x91, 0x5d, 0x06, 0xb6, 0x7a, 0xb2, 0x9e, 0xfe, 0x79, 0x80, 0x28, 0x99, 0x4e, 0x63,
	0x55, 0x78, 0xea, 0x17, 0x10, 0x4c, 0x3b, 0x8b, 0xa2, 0xd9, 0x34, 0xb4, 0xbf, 0xeb, 0x1c, 0x6b,
	0x18, 0x8c, 0x1a, 0xc8, 0x2c, 0x19, 0x2a, 0x2e, 0xb4, 0xe9, 0x7b, 0xca, 0x39, 0xd7, 0xb0, 0x18,
	0xf6, 0x3d, 0x15, 0xfc, 0xd6, 0x03, 0xb8, 0xcc, 0xc2, 0xfb, 0x3a, 0xf7, 0x00, 0x9a, 0xc9, 0x1b,
	0xc1, 0xd3, 0x7c, 0x95, 0x75, 0x6d, 0xd3, 0x80, 0xef, 0x88, 0x80, 0x77, 0x43, 0x04, 0x36, 0xde,
	0x11, 0x81, 0xca, 0x5b, 0x11, 0x38, 0x81, 0xaa, 0xa1, 0x45, 0xc7, 0xbc, 0xf7, 0xec, 0x0a, 0x57,
	0x94, 0x5e, 0xd7, 0x98, 0x41, 0x1d, 0x17, 0x4e, 0x7b, 0x51, 0xca, 0x99, 0xe6, 0xa3, 0x90, 0xb9,
	0xd1, 0xc0, 0x0d, 0xb0, 0x5b, 0x0e, 0x3f, 0xb0, 0x83, 0x01, 0x3e, 0xac, 0xdc, 0xa8, 0x87, 0x6f,
	0x92, 0x12, 0x75, 0x52, 0x30, 0x32, 0x0f, 0xab, 0x73, 0x73, 0xab, 0x9a, 0x88, 0x64, 0xb7, 0xaa,
	0x11, 0xf0, 0xfe, 0x8d, 0x92, 0x58, 0x64, 0xf7, 0x2f, 0x7e, 0x5f, 0xde, 0xbf, 0x5e, 0xe1, 0xfe,
	0xc5, 0xa6, 0x84, 0xb1, 0xb3, 0x1a, 0x1b, 0x1b, 0x7f, 0x18, 0xcb, 0x53, 0x94, 0x83, 0x3f, 0x96,
	0xa0, 0xe6, 0x2a, 0xbd, 0x38, 0x6b, 0x94, 0x96, 0x67, 0x8d, 0x97, 0x50, 0x1b, 0xb2, 0x09, 0xb3,
	0x4d, 0xd9, 0x7b, 0xcf, 0xa6, 0xbc, 0x7a, 0x92, 0xba, 0x8f, 0x2c, 0x05, 0xcd, 0xb8, 0xd0, 0x5e,
	0x91, 0x20, 0xa9, 0xb3, 0xd7, 0x08, 0xc1, 0x43, 0xa8, 0xb9, 0x95, 0xb9, 0x93, 0xa5, 0xab, 0x9c,
	0x2c, 0x17, 0x87, 0x8c, 0x57, 0x70, 0xeb, 0x59, 0x2c, 0x9e, 0x32, 0x75, 0x9c, 0xc6, 0x11, 0xff,
	0x80, 0x39, 0xe3, 0xf6, 0xd2, 0x9c, 0x51, 0xcf, 0x66, 0x89, 0xde, 0xef, 0xcb, 0xd0, 0x38, 0xd2,
	0x5a, 0x0e, 0x78, 0x3a, 0x8f, 0x23, 0x4e, 0x9e, 0x40, 0xd5, 0x0d, 0xd6, 0xb7, 0xbb, 0xf6, 0x3f,
	0x80, 0xdd, 0xec, 0x3f, 0x80, 0xdd, 0x27, 0x53, 0xa9, 0x17, 0x01, 0x79, 0x7b, 0x0e, 0xeb, 0xb4,
	0x7e, 0xf2, 0xb7, 0x7f, 0xff, 0xac, 0x5c, 0x27, 0xb5, 0x7d, 0x9b, 0x5d, 0xd2, 0x87, 0x9a, 0x7b,
	0x9c, 0x5f, 0xcb, 0x73, 0xeb, 0x8a, 0x17, 0x7c, 0x67, 0xc7, 0x10, 0x35, 0x48, 0x7d, 0x5f, 0x70,
	0x6d, 0x26, 0x6b, 0x72, 0x0a, 0x8d, 0x82, 0xeb, 0xd7, 0xd2, 0xdd, 0x41, 0xba, 0x2b, 0x62, 0xd4,
	0xb9, 0x6d, 0x28, 0xb7, 0xc9, 0xd6, 0xfe, 0x34, 0x16, 0xd8, 0xdd, 0x42, 0x69, 0x88, 0x8e, 0x2e,
	0x67, 0x9f, 0x77, 0x9a, 0xb8, 0x52, 0x06, 0x9d, 0x6d, 0xc3, 0x07, 0xc4, 0xdf, 0x77, 0xb3, 0xd1,
	0xb0, 0x6a, 0xb6, 0x3d, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xf2, 0xa9, 0x32, 0x61,
	0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HttpServiceClient is the client API for HttpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HttpServiceClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	NetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetInfoResponse, error)
	MinGasPrice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MinGasPriceResponse, error)
	Genesis(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenesisResponse, error)
}

type httpServiceClient struct {
	cc *grpc.ClientConn
}

func NewHttpServiceClient(cc *grpc.ClientConn) HttpServiceClient {
	return &httpServiceClient{cc}
}

func (c *httpServiceClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/pb.HttpService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpServiceClient) NetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetInfoResponse, error) {
	out := new(NetInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.HttpService/NetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpServiceClient) MinGasPrice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MinGasPriceResponse, error) {
	out := new(MinGasPriceResponse)
	err := c.cc.Invoke(ctx, "/pb.HttpService/MinGasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpServiceClient) Genesis(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenesisResponse, error) {
	out := new(GenesisResponse)
	err := c.cc.Invoke(ctx, "/pb.HttpService/Genesis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpServiceServer is the server API for HttpService service.
type HttpServiceServer interface {
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	NetInfo(context.Context, *empty.Empty) (*NetInfoResponse, error)
	MinGasPrice(context.Context, *empty.Empty) (*MinGasPriceResponse, error)
	Genesis(context.Context, *empty.Empty) (*GenesisResponse, error)
}

// UnimplementedHttpServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHttpServiceServer struct {
}

func (*UnimplementedHttpServiceServer) Status(ctx context.Context, req *empty.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedHttpServiceServer) NetInfo(ctx context.Context, req *empty.Empty) (*NetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetInfo not implemented")
}
func (*UnimplementedHttpServiceServer) MinGasPrice(ctx context.Context, req *empty.Empty) (*MinGasPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MinGasPrice not implemented")
}
func (*UnimplementedHttpServiceServer) Genesis(ctx context.Context, req *empty.Empty) (*GenesisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Genesis not implemented")
}

func RegisterHttpServiceServer(s *grpc.Server, srv HttpServiceServer) {
	s.RegisterService(&_HttpService_serviceDesc, srv)
}

func _HttpService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HttpService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpServiceServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpService_NetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpServiceServer).NetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HttpService/NetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpServiceServer).NetInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpService_MinGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpServiceServer).MinGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HttpService/MinGasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpServiceServer).MinGasPrice(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpService_Genesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpServiceServer).Genesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HttpService/Genesis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpServiceServer).Genesis(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _HttpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HttpService",
	HandlerType: (*HttpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HttpService_Status_Handler,
		},
		{
			MethodName: "NetInfo",
			Handler:    _HttpService_NetInfo_Handler,
		},
		{
			MethodName: "MinGasPrice",
			Handler:    _HttpService_MinGasPrice_Handler,
		},
		{
			MethodName: "Genesis",
			Handler:    _HttpService_Genesis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "http.proto",
}
